# NumPy Demo
NumPy is a package for scientific computing with Python. For more information, click [here](https://numpy.org/doc/stable/) to check out the documentation.

In [1]:
import numpy as np

## Array Creation and Indexing

In [2]:
# convert list to numpy array
a = np.array([2,7,1])
print("1d array: a: {}".format(a))
print("1d array: a.shape: {}".format(a.shape))
print("Index into array entry index 2: {}".format(a[2]))

1d array: a: [2 7 1]
1d array: a.shape: (3,)
Index into array entry index 2: 1


In [3]:
# example: 2d-array as row vector
# A = [2,7,1]
# Define A as list of list for each row
A = np.array([[2,7,1]])
print("2d row matrix: A: {}".format(A))
print("2d row matrix: A.shape: {}".format(A.shape))
print("Index into matrix entry index row=0,col=2: {}".format(A[0,2]))

2d row matrix: A: [[2 7 1]]
2d row matrix: A.shape: (1, 3)
Index into matrix entry index row=0,col=2: 1


In [4]:
# example: 2d-array as column vector
# each row is a list
# Define B as list of list for each row
# B = [2]
#     [7]
#     [1]
B = np.array([[2],[7],[1]])
print("2d column matrix: B: \n{}".format(B))
print("2d column matrix: B.shape: {}".format(B.shape))
print("Index into matrix entry index row=1,col=0: {}".format(B[1,0]))

2d column matrix: B: 
[[2]
 [7]
 [1]]
2d column matrix: B.shape: (3, 1)
Index into matrix entry index row=1,col=0: 7


In [5]:
# example: matrix
# X = [1 2 3]
#     [4 5 6]
# Define X as list of list for each row
X = np.array([[1,2,3],[4,5,6]])
print("2d array: X: \n{}".format(X))
print("2d array: X.shape: {}".format(X.shape))
print("Index into matrix entry index row=1,col=1: {}".format(X[1,1]))

2d array: X: 
[[1 2 3]
 [4 5 6]]
2d array: X.shape: (2, 3)
Index into matrix entry index row=1,col=1: 5


## Component-wise Operations

In [6]:
# X = [1 2 3]
#     [4 5 6]
# Y = [1 -1  2]
#     [2  3 -2]
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,-1,2],[2,3,-2]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))

X: 
[[1 2 3]
 [4 5 6]]
Y: 
[[ 1 -1  2]
 [ 2  3 -2]]


### Component-wise Addition
Component-wise addition, the result will be an array of the same dimension as the inputs

In [7]:
Z1 = X + Y
print("Z1=X+Y: \n{}".format(Z1))

Z1=X+Y: 
[[2 1 5]
 [6 8 4]]


### Scalar Multiplication
Multiply each element by a scalar

In [8]:
Z2 = 2*X
print("Z2=2*X: \n{}".format(Z2))

Z2=2*X: 
[[ 2  4  6]
 [ 8 10 12]]


### Component-wise Multipication
Component-wise multiplication (this is not matrix multiplication), the result will be an array of the same dimension as the inputs

In [9]:
Z3 = X*Y
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
print("Z3=X*Y: \n{}".format(Z3))

X: 
[[1 2 3]
 [4 5 6]]
Y: 
[[ 1 -1  2]
 [ 2  3 -2]]
Z3=X*Y: 
[[  1  -2   6]
 [  8  15 -12]]


## Functions

### Exponential
Take the exponential of each element

In [10]:
Xexp = np.exp(X)
print("X: \n{}".format(X))
print("Exponential of X: \n{}".format(Xexp))

X: 
[[1 2 3]
 [4 5 6]]
Exponential of X: 
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


### Absolute Value
Take the abslute value of each element

In [11]:
Yabs = np.absolute(Y)
print("Y: \n{}".format(Y))
print("Absolute Value of Y: \n{}".format(Yabs))

Y: 
[[ 1 -1  2]
 [ 2  3 -2]]
Absolute Value of Y: 
[[1 1 2]
 [2 3 2]]


### Square
Take the square of each element

In [12]:
Xsq = np.square(X)
print("X: \n{}".format(X))
print("Square of X: \n{}".format(Xsq))

X: 
[[1 2 3]
 [4 5 6]]
Square of X: 
[[ 1  4  9]
 [16 25 36]]


## Concatenation

In [13]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,-1,2],[2,3,-2]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))
# concatenation - in row direction - use axis=0 in 2nd input
# result is [1  2  3]
#           [4  5  6]
#           [1 -1  2]
#           [2  3 -2]
XandYrow = np.concatenate((X,Y),axis=0)
print("X and Y concatenated in row direction: \n{}".format(XandYrow))
# concatenation X and Y - in column direction - use axis=1 in 2nd input
# result is [1 2 3 1 -1  2]
#           [4 5 6 2  3 -2]
XandYcol = np.concatenate((X,Y),axis=1)
print("X and Y concatenated in column direction: \n{}".format(XandYcol))

X: 
[[1 2 3]
 [4 5 6]]
Y: 
[[ 1 -1  2]
 [ 2  3 -2]]
X and Y concatenated in row direction: 
[[ 1  2  3]
 [ 4  5  6]
 [ 1 -1  2]
 [ 2  3 -2]]
X and Y concatenated in column direction: 
[[ 1  2  3  1 -1  2]
 [ 4  5  6  2  3 -2]]


## Reshaping

In [14]:
# reshape X into matrix 1 row 6 columns: [1 2 3 4 5 6]
print("X: \n{}".format(X))
Xreshaperow = np.reshape(X,(1,6))
print("X reshape row vector: \n{}".format(Xreshaperow))
Xreshapecol = np.reshape(X,(6,1))
print("X reshape col vector: \n{}".format(Xreshapecol))

X: 
[[1 2 3]
 [4 5 6]]
X reshape row vector: 
[[1 2 3 4 5 6]]
X reshape col vector: 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## Removing Axes

In [15]:
# start with row vector (2d np.array) and convert to 1d np.array
A = np.array([[1,2,3]])
print("A: {}".format(A))
print("A.shape: {}".format(A.shape))
# removes axis with only 1 entry in dimension
A1 = np.squeeze(A) 
print("A1: {}".format(A1))
print("A1.shape: {}".format(A1.shape))

A: [[1 2 3]]
A.shape: (1, 3)
A1: [1 2 3]
A1.shape: (3,)


## Adding Axes

In [16]:
# start with 1d array and make into 2d array using np.expand_dims
a = np.array([1,2,3])
print("a: {}".format(a))
print("a.shape: {}".format(a.shape))
# add dimension to make into a row vector
b = np.expand_dims(a,axis=0)
print("b: \n{}".format(b))
print("b.shape: {}".format(b.shape))
# add dimension to make into a column vector 
c = np.expand_dims(a,axis=1)
print("c: \n{}".format(c))
print("c.shape: {}".format(c.shape))

a: [1 2 3]
a.shape: (3,)
b: 
[[1 2 3]]
b.shape: (1, 3)
c: 
[[1]
 [2]
 [3]]
c.shape: (3, 1)


## Summing Entries

In [17]:
# X = [1 2 3]
#     [4 5 6]
X = np.array([[1,2,3],[4,5,6]])
print("X: \n{}".format(X))
# sum all entries
sum1 = np.sum(X)
print("sum entries of x: {}".format(sum1))

X: 
[[1 2 3]
 [4 5 6]]
sum entries of x: 21


In [18]:
# sum in row direction - this removes an axis -> 1d array [5 7 9]
rowsum1 = np.sum(X,axis=0)
print("sum in row direction X: \n{}".format(rowsum1))
print("rowsum1.shape: {}".format(rowsum1.shape))

sum in row direction X: 
[5 7 9]
rowsum1.shape: (3,)


In [19]:
# sum in row direction - keep row axis -> row matrix [5 7 9]
rowsum2 = np.sum(X,axis=0,keepdims=True)
print("sum in row direction X keep row axis: \n{}".format(rowsum2))
print("rowsum2.shape: {}".format(rowsum2.shape))

sum in row direction X keep row axis: 
[[5 7 9]]
rowsum2.shape: (1, 3)


In [20]:
# sum in column direction - keep column axis -> 2darray
colsum1 = np.sum(X,axis=1,keepdims=True)
print("sum in column direction keep col axis: \n{}".format(colsum1))
print("colsum1.shape: {}".format(colsum1.shape))

sum in column direction keep col axis: 
[[ 6]
 [15]]
colsum1.shape: (2, 1)


## Array of Zeros

In [21]:
# generate zero matrix dimension (3,2)
Z0 = np.zeros((3,2))
print("zero matrix: \n{}".format(Z0))

zero matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


## Array of Ones

In [22]:
# generate ones matrix dimension (2,3)
Z1 = np.ones((2,3))
print("ones matrix: \n{}".format(Z1))

ones matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]


## Array of Random Numbers

In [23]:
# generate random matrix  dim (2,3) - uniform distribution
Runiform = np.random.rand(2,3)
print("Runiform: \n{}".format(Runiform))

Runiform: 
[[0.93028514 0.30738971 0.85240687]
 [0.96460489 0.15750789 0.30364947]]


In [24]:
# generate random matrix  dim (2,3) - normal distribution
# set seed first
np.random.seed(10)
Rnormal = np.random.randn(2,3)
print("Rnormal: \n{}".format(Rnormal))

Rnormal: 
[[ 1.3315865   0.71527897 -1.54540029]
 [-0.00838385  0.62133597 -0.72008556]]
